config/routes.rb
Rails.application.routes.draw do

  root :to => 'session#new'
  resources :reservations
  resources :flights
  resources :airplanes
  resources :users

  get '/search' => 'pages#search' , :as => 'search_flights'
  get '/contact' => 'pages#contact' , :as => 'contact_us'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/airplane.rb
# == Schema Information
#
# Table name: airplanes
#
#  id         :integer          not null, primary key
#  name       :text
#  rows       :integer
#  columns    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Airplane < ActiveRecord::Base
  has_many :flights
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:name, :rows, :columns)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_for(@airplane) do |f| %>
  <% if @airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% @airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <%= f.label :rows %><br>
    <%= f.number_field :rows %>
  </div>
  <div class="field">
    <%= f.label :columns %><br>
    <%= f.number_field :columns %>
  </div>
</br>
</br>
  <div class="actions">
    <%= f.submit :class => 'airplanebuttons'%>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form' %>


</br>
<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Airplanes</h1>

<table class ="airplaneindex">
  <thead>
    <tr>
      <th>Name</th>
      <th>Rows</th>
      <th>Columns</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.name %></td>
        <td><%= airplane.rows %></td>
        <td><%= airplane.columns %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form' %>

</br>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>





<!-- <div class="container">
<% @airplane.rows.times do |r| %>

  <div class="longrow" >

  <% @airplane.columns.times do |c| %>

    <div class="cell"> </div>
  <% end %>

<% end %>

</div> -->



<p>
  <strong>Columns:</strong>
  <%= @airplane.columns %>
</p>
  <table class="seats">
    <tr>
      <td></td>
      <% (@airplane.rows).times do |row| %>
      <td> <%= row+1 %></td>
      <% end %>
    </tr>
    <% (@airplane.columns).times do |col| %>
    <tr>
      <td>
        <%= (('A'..'Z').to_a)[col] %>
      </td>
      <% (@airplane.rows).times do |row| %>
      <td class="planeSeats" id="<%= (('A'..'Z').to_a)[col]+(row+1).to_s %>">
        avail
      </td>
      <% end %>
    </tr>
    <% end %>
  </table>

</div>


<div class="controls col-xs-offset-4 col-md-offset-4 col-xs-4 col-md-4">
  <%= link_to 'Edit', edit_airplane_path(@airplane) %> |
  <%= link_to 'Back', airplanes_path %>
</div>