config/routes.rb
Rails.application.routes.draw do

  root :to => 'session#new'
  resources :reservations
  resources :flights
  resources :airplanes
  resources :users

  get '/search' => 'pages#search' , :as => 'search_flights'
  get '/contact' => 'pages#contact' , :as => 'contact_us'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>BurningAirlines</title>
        <meta charset="UTF-8">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
    <% if @current_user.present? %>
      <script>
var app = app || {};
app.current_user = <%= @current_user.id %>;
      </script>
    <% end %>
        <header class="container-fluid">
            <h1 class="header-heading">Burning Airlines</h1>
            <h4>
                <span class="header-text-highlight">A Production by Team Tripti</span>
            </h4>
        </header>

        <nav>
            <ul class="nav nav-tabs options">
                <li><%= link_to 'Home <span class="glyphicon glyphicon-home" aria-hidden="true"></span>'.html_safe, search_flights_path %></li>
                <li><%= link_to 'Flights <span class="glyphicon glyphicon-cloud" aria-hidden="true"></span>'.html_safe, flights_path %></li>
               <li><%= link_to 'Planes <span class="glyphicon glyphicon-plane" aria-hidden="true"></span>'.html_safe, airplanes_path %></li>
                <% if !(@current_user.present?) %>
                <li role="presentation" class="<%= 'active' if params[:controller] == 'controller1' %>">
                    <%= link_to 'Create account <span class="glyphicon glyphicon-user" aria-hidden="true"></span>'.html_safe , new_user_path %>
                </li>
                <li role="presentation" class="<%= 'active' if params[:controller] == 'controller2' %>">
                    <%= link_to 'Log In <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>'.html_safe,login_path %>
                </li>
            <% else %>
                <li role="presentation" class="<%= 'active' if params[:controller] == 'controller3' %>">
                    <%= link_to 'Logout <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>'.html_safe,login_path,:method => 'delete' %>
                </li>
                <li role="presentation" class="<%= 'active' if params[:controller] == 'controller4' %>">
                    <%= link_to @current_user.name,user_path(@current_user.id) %>
                </li>
                <% end %>
                <li role="presentation" class="<%= 'active' if params[:controller] == 'controller5' %>">
                    <%= link_to 'Contact Us <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span>'.html_safe ,contact_us_path %>
                </li>
            </ul>
        </nav>

        <div class="container yeild-wrapper row">
          <div class="col-md-4"></div>

          <div class="col-md-4">
            <% if flash[:alert] %>
              <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
            <% end %>

            <%= yield %>
          </div>

          <div class="col-md-4"></div>
        </div>

        <footer class="container-fluid">
            <div class="social-icons"></div>

            <div class="copyright-notice">
                <p>&copy;2016 Team Tripti. All rights reserved</p>
            </div>
        </footer>

    </body>
</html>